# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import payoneer_mobile_api
from payoneer_mobile_api.rest import ApiException
from payoneer_mobile_api.apis.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """ AuthenticationApi unit test stubs """

    def setUp(self):
        self.api = payoneer_mobile_api.apis.authentication_api.AuthenticationApi()

    def tearDown(self):
        pass

    def test_authentication_challenge_authenticate_post(self):
        """
        Test case for authentication_challenge_authenticate_post

        ChallengeAuthenticate
        """
        pass

    def test_authentication_challenge_cancel_post(self):
        """
        Test case for authentication_challenge_cancel_post

        ChallengeCancel
        """
        pass

    def test_authentication_challenge_get_post(self):
        """
        Test case for authentication_challenge_get_post

        ChallengeGet
        """
        pass

    def test_authentication_challenge_refuse_sms_post(self):
        """
        Test case for authentication_challenge_refuse_sms_post

        ChallengeRefuseSms
        """
        pass

    def test_authentication_challenge_sms_post(self):
        """
        Test case for authentication_challenge_sms_post

        ChallengeSms
        """
        pass


if __name__ == '__main__':
    unittest.main()
