# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import payoneer_mobile_api
from payoneer_mobile_api.rest import ApiException
from payoneer_mobile_api.apis.transaction_api import TransactionApi


class TestTransactionApi(unittest.TestCase):
    """ TransactionApi unit test stubs """

    def setUp(self):
        self.api = payoneer_mobile_api.apis.transaction_api.TransactionApi()

    def tearDown(self):
        pass

    def test_transaction_pre_auth_transactions_post(self):
        """
        Test case for transaction_pre_auth_transactions_post

        Pre-Authorization Transactions
        """
        pass

    def test_transaction_transaction_details_post(self):
        """
        Test case for transaction_transaction_details_post

        Transaction Details
        """
        pass

    def test_transaction_transactions_post(self):
        """
        Test case for transaction_transactions_post

        Transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
