# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import payoneer_mobile_api
from payoneer_mobile_api.rest import ApiException
from payoneer_mobile_api.apis.balance_api import BalanceApi


class TestBalanceApi(unittest.TestCase):
    """ BalanceApi unit test stubs """

    def setUp(self):
        self.api = payoneer_mobile_api.apis.balance_api.BalanceApi()

    def tearDown(self):
        pass

    def test_balance_balance_post(self):
        """
        Test case for balance_balance_post

        Balance
        """
        pass


if __name__ == '__main__':
    unittest.main()
