# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import payoneer_mobile_api
from payoneer_mobile_api.rest import ApiException
from payoneer_mobile_api.apis.payment_api import PaymentApi


class TestPaymentApi(unittest.TestCase):
    """ PaymentApi unit test stubs """

    def setUp(self):
        self.api = payoneer_mobile_api.apis.payment_api.PaymentApi()

    def tearDown(self):
        pass

    def test_payment_payment_details_post(self):
        """
        Test case for payment_payment_details_post

        Payment Details
        """
        pass

    def test_payment_payments_post(self):
        """
        Test case for payment_payments_post

        Payments
        """
        pass


if __name__ == '__main__':
    unittest.main()
