# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AccountPermission(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, per_id=None, per_val=None):
        """
        AccountPermission - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'per_id': 'int',
            'per_val': 'bool'
        }

        self.attribute_map = {
            'per_id': 'PerId',
            'per_val': 'PerVal'
        }

        self._per_id = per_id
        self._per_val = per_val

    @property
    def per_id(self):
        """
        Gets the per_id of this AccountPermission.

        :return: The per_id of this AccountPermission.
        :rtype: int
        """
        return self._per_id

    @per_id.setter
    def per_id(self, per_id):
        """
        Sets the per_id of this AccountPermission.

        :param per_id: The per_id of this AccountPermission.
        :type: int
        """

        self._per_id = per_id

    @property
    def per_val(self):
        """
        Gets the per_val of this AccountPermission.

        :return: The per_val of this AccountPermission.
        :rtype: bool
        """
        return self._per_val

    @per_val.setter
    def per_val(self, per_val):
        """
        Sets the per_val of this AccountPermission.

        :param per_val: The per_val of this AccountPermission.
        :type: bool
        """

        self._per_val = per_val

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AccountPermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
