# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PaymentMethodDetailsResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, response_code=None, balance=None, recent_payments=None, last_transactions=None):
        """
        PaymentMethodDetailsResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'response_code': 'int',
            'balance': 'PaymentMethodBalance',
            'recent_payments': 'list[PaymentHeaderResponse]',
            'last_transactions': 'list[TransactionHeaderResponse]'
        }

        self.attribute_map = {
            'response_code': 'ResponseCode',
            'balance': 'Balance',
            'recent_payments': 'RecentPayments',
            'last_transactions': 'LastTransactions'
        }

        self._response_code = response_code
        self._balance = balance
        self._recent_payments = recent_payments
        self._last_transactions = last_transactions

    @property
    def response_code(self):
        """
        Gets the response_code of this PaymentMethodDetailsResponse.
        1 - Success; 34 - (Assumption) Terms&Conditions not agreed;

        :return: The response_code of this PaymentMethodDetailsResponse.
        :rtype: int
        """
        return self._response_code

    @response_code.setter
    def response_code(self, response_code):
        """
        Sets the response_code of this PaymentMethodDetailsResponse.
        1 - Success; 34 - (Assumption) Terms&Conditions not agreed;

        :param response_code: The response_code of this PaymentMethodDetailsResponse.
        :type: int
        """

        self._response_code = response_code

    @property
    def balance(self):
        """
        Gets the balance of this PaymentMethodDetailsResponse.

        :return: The balance of this PaymentMethodDetailsResponse.
        :rtype: PaymentMethodBalance
        """
        return self._balance

    @balance.setter
    def balance(self, balance):
        """
        Sets the balance of this PaymentMethodDetailsResponse.

        :param balance: The balance of this PaymentMethodDetailsResponse.
        :type: PaymentMethodBalance
        """

        self._balance = balance

    @property
    def recent_payments(self):
        """
        Gets the recent_payments of this PaymentMethodDetailsResponse.

        :return: The recent_payments of this PaymentMethodDetailsResponse.
        :rtype: list[PaymentHeaderResponse]
        """
        return self._recent_payments

    @recent_payments.setter
    def recent_payments(self, recent_payments):
        """
        Sets the recent_payments of this PaymentMethodDetailsResponse.

        :param recent_payments: The recent_payments of this PaymentMethodDetailsResponse.
        :type: list[PaymentHeaderResponse]
        """

        self._recent_payments = recent_payments

    @property
    def last_transactions(self):
        """
        Gets the last_transactions of this PaymentMethodDetailsResponse.

        :return: The last_transactions of this PaymentMethodDetailsResponse.
        :rtype: list[TransactionHeaderResponse]
        """
        return self._last_transactions

    @last_transactions.setter
    def last_transactions(self, last_transactions):
        """
        Sets the last_transactions of this PaymentMethodDetailsResponse.

        :param last_transactions: The last_transactions of this PaymentMethodDetailsResponse.
        :type: list[TransactionHeaderResponse]
        """

        self._last_transactions = last_transactions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PaymentMethodDetailsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
