# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SignDocumentsRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, device_id=None, mac=None, is_first_app_start=None):
        """
        SignDocumentsRequest - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'device_id': 'DeviceId',
            'mac': 'str',
            'is_first_app_start': 'bool'
        }

        self.attribute_map = {
            'device_id': 'DeviceId',
            'mac': 'MAC',
            'is_first_app_start': 'IsFirstAppStart'
        }

        self._device_id = device_id
        self._mac = mac
        self._is_first_app_start = is_first_app_start

    @property
    def device_id(self):
        """
        Gets the device_id of this SignDocumentsRequest.

        :return: The device_id of this SignDocumentsRequest.
        :rtype: DeviceId
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """
        Sets the device_id of this SignDocumentsRequest.

        :param device_id: The device_id of this SignDocumentsRequest.
        :type: DeviceId
        """
        if device_id is None:
            raise ValueError("Invalid value for `device_id`, must not be `None`")

        self._device_id = device_id

    @property
    def mac(self):
        """
        Gets the mac of this SignDocumentsRequest.

        :return: The mac of this SignDocumentsRequest.
        :rtype: str
        """
        return self._mac

    @mac.setter
    def mac(self, mac):
        """
        Sets the mac of this SignDocumentsRequest.

        :param mac: The mac of this SignDocumentsRequest.
        :type: str
        """

        self._mac = mac

    @property
    def is_first_app_start(self):
        """
        Gets the is_first_app_start of this SignDocumentsRequest.

        :return: The is_first_app_start of this SignDocumentsRequest.
        :rtype: bool
        """
        return self._is_first_app_start

    @is_first_app_start.setter
    def is_first_app_start(self, is_first_app_start):
        """
        Sets the is_first_app_start of this SignDocumentsRequest.

        :param is_first_app_start: The is_first_app_start of this SignDocumentsRequest.
        :type: bool
        """
        if is_first_app_start is None:
            raise ValueError("Invalid value for `is_first_app_start`, must not be `None`")

        self._is_first_app_start = is_first_app_start

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SignDocumentsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
