# coding: utf-8

"""
    Payoneer Mobile API

    Swagger specification for https://mobileapi.payoneer.com

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SupportedLanguageResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, language_code=None, display_name=None, is_rtl=None, iso_code=None):
        """
        SupportedLanguageResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'language_code': 'LanguageCode',
            'display_name': 'str',
            'is_rtl': 'bool',
            'iso_code': 'str'
        }

        self.attribute_map = {
            'language_code': 'LanguageCode',
            'display_name': 'DisplayName',
            'is_rtl': 'IsRTL',
            'iso_code': 'ISOCode'
        }

        self._language_code = language_code
        self._display_name = display_name
        self._is_rtl = is_rtl
        self._iso_code = iso_code

    @property
    def language_code(self):
        """
        Gets the language_code of this SupportedLanguageResponse.

        :return: The language_code of this SupportedLanguageResponse.
        :rtype: LanguageCode
        """
        return self._language_code

    @language_code.setter
    def language_code(self, language_code):
        """
        Sets the language_code of this SupportedLanguageResponse.

        :param language_code: The language_code of this SupportedLanguageResponse.
        :type: LanguageCode
        """

        self._language_code = language_code

    @property
    def display_name(self):
        """
        Gets the display_name of this SupportedLanguageResponse.

        :return: The display_name of this SupportedLanguageResponse.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """
        Sets the display_name of this SupportedLanguageResponse.

        :param display_name: The display_name of this SupportedLanguageResponse.
        :type: str
        """

        self._display_name = display_name

    @property
    def is_rtl(self):
        """
        Gets the is_rtl of this SupportedLanguageResponse.

        :return: The is_rtl of this SupportedLanguageResponse.
        :rtype: bool
        """
        return self._is_rtl

    @is_rtl.setter
    def is_rtl(self, is_rtl):
        """
        Sets the is_rtl of this SupportedLanguageResponse.

        :param is_rtl: The is_rtl of this SupportedLanguageResponse.
        :type: bool
        """

        self._is_rtl = is_rtl

    @property
    def iso_code(self):
        """
        Gets the iso_code of this SupportedLanguageResponse.

        :return: The iso_code of this SupportedLanguageResponse.
        :rtype: str
        """
        return self._iso_code

    @iso_code.setter
    def iso_code(self, iso_code):
        """
        Sets the iso_code of this SupportedLanguageResponse.

        :param iso_code: The iso_code of this SupportedLanguageResponse.
        :type: str
        """

        self._iso_code = iso_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SupportedLanguageResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
